---
deployment:
  tasks:

    # DEBUG
    - /opt/cpanel/ea-php83/root/usr/bin/php -v
    - /usr/local/bin/composer --version
    - /opt/cpanel/ea-php83/root/usr/bin/php /usr/local/bin/composer check-platform-reqs --working-dir=/home/onevsbmm/ngekosin > /home/onevsbmm/public_html/platform-check.txt 2>&1

    # Composer
    - /opt/cpanel/ea-php83/root/usr/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir=/home/onevsbmm/ngekosin

    # Copy Laravel public
    - /bin/cp -R public/* /home/onevsbmm/public_html/

    # Copy .htaccess Laravel
    - /bin/cp public/.htaccess /home/onevsbmm/public_html/.htaccess

    # Perbaiki path Laravel di index.php
    - /bin/sed -i "s#__DIR__.'/../storage/framework/maintenance.php'#__DIR__.'/../ngekosin/storage/framework/maintenance.php'#" /home/onevsbmm/public_html/index.php
    - /bin/sed -i "s#__DIR__.'/../vendor/autoload.php'#__DIR__.'/../ngekosin/vendor/autoload.php'#" /home/onevsbmm/public_html/index.php
    - /bin/sed -i "s#__DIR__.'/../bootstrap/app.php'#__DIR__.'/../ngekosin/bootstrap/app.php'#" /home/onevsbmm/public_html/index.php

    # Migration dengan PHP 8.3
    - cd /home/onevsbmm/ngekosin && /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force

    # Seeder dengan PHP 8.3
    - cd /home/onevsbmm/ngekosin && /opt/cpanel/ea-php83/root/usr/bin/php artisan db:seed --force

    # Storage link dengan PHP 8.3
    - cd /home/onevsbmm/ngekosin && /opt/cpanel/ea-php83/root/usr/bin/php artisan storage:link