---
deployment:
  tasks:
    - /bin/sh -c "command -v composer > /home/onevsbmm/public_html/composer-check.txt 2>&1 || true"
    - /bin/sh -c "php -v >> /home/onevsbmm/public_html/composer-check.txt 2>&1 || true"

# ---
# deployment:
#   tasks:
#     - /bin/cp -R public/* /home/onevsbmm/public_html/
#     - /bin/sed -i "s#__DIR__.'/../storage/framework/maintenance.php'#__DIR__.'/../ngekosin/storage/framework/maintenance.php'#" /home/onevsbmm/public_html/index.php
#     - /bin/sed -i "s#__DIR__.'/../vendor/autoload.php'#__DIR__.'/../ngekosin/vendor/autoload.php'#" /home/onevsbmm/public_html/index.php
#     - /bin/sed -i "s#__DIR__.'/../bootstrap/app.php'#__DIR__.'/../ngekosin/bootstrap/app.php'#" /home/onevsbmm/public_html/index.php
