---
deployment:
  tasks:
    # Install dependency Laravel menggunakan PHP 8.3
    - /opt/cpanel/ea-php83/root/usr/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --working-dir=/home/onevsbmm/ngekosin

    # Copy folder public Laravel ke document root
    - /bin/cp -R public/* /home/onevsbmm/public_html/

    # Perbaiki path Laravel di index.php
    - /bin/sed -i "s#__DIR__.'/../storage/framework/maintenance.php'#__DIR__.'/../ngekosin/storage/framework/maintenance.php'#" /home/onevsbmm/public_html/index.php
    - /bin/sed -i "s#__DIR__.'/../vendor/autoload.php'#__DIR__.'/../ngekosin/vendor/autoload.php'#" /home/onevsbmm/public_html/index.php
    - /bin/sed -i "s#__DIR__.'/../bootstrap/app.php'#__DIR__.'/../ngekosin/bootstrap/app.php'#" /home/onevsbmm/public_html/index.php

    - cd /home/onevsbmm/ngekosin && /opt/cpanel/ea-php83/root/usr/bin/php artisan about > /home/onevsbmm/public_html/laravel-about.txt 2>&1
    - cd /home/onevsbmm/ngekosin && /opt/cpanel/ea-php83/root/usr/bin/php artisan migrate --force > /home/onevsbmm/public_html/migrate-result.txt 2>&1
